name: cgm_app
description: Child Growth Monitor - Malnutrition Screening & Nutrition Intelligence App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State Management
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  
  # Excel Import/Export
  syncfusion_flutter_xlsio: ^29.2.11
  file_picker: ^5.3.2
  
  # Camera & Image Processing
  camera: ^0.10.5
  image_picker: ^0.8.9
  image: ^4.0.17
  
  # ML Models
  tflite_flutter: ^0.10.1
  google_mlkit_pose_detection: ^0.8.0
  
  # Location
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  
  # UI Components
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  intl: ^0.20.2
  community_charts_flutter: ^1.0.0
  
  # Export
  csv: ^5.0.2
  pdf: ^3.10.4
  printing: ^5.11.0
  
  # Networking
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  
  # Utils
  uuid: ^3.0.7
  logger: ^1.4.0
  shared_preferences: ^2.2.0
  
  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/ml_models/
    - assets/data/
    - assets/images/