# Netlify Configuration for She&Her Healthcare Platform
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Cache manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache"

# Environment variables for production
[context.production.environment]
  VITE_CONVEX_URL = "https://clever-grouse-917.convex.cloud"
  SITE_PASSWORD = "SheHerSecure2025!"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  VITE_CONVEX_URL = "https://clever-grouse-917.convex.cloud"
  SITE_PASSWORD = "SheHerSecure2025!"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  VITE_CONVEX_URL = "https://clever-grouse-917.convex.cloud"
  SITE_PASSWORD = "SheHerSecure2025!"

# Functions directory (if you add serverless functions later)
[functions]
  directory = "netlify/functions"
