# 🚀 AIRDOCS - Fly.io Configuration
app = "airdocs"
primary_region = "iad"

[build]

[env]
  ENVIRONMENT = "production"
  DEBUG = "false"
  API_HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
